[[language]]
name = "rust"
indent = { tab-width = 4, unit = "\t" }
includeInlayEnumMemberValueHints = true
includeInlayFunctionLikeReturnTypeHints = true
includeInlayFunctionParameterTypeHints = true
includeInlayParameterNameHints = "literals"                       # 'none' | 'literals' | 'all';
includeInlayParameterNameHintsWhenArgumentMatchesName = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayVariableTypeHints = true
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
# inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.lifetimeElisionHints.enable = false
inlayHints.typeHints.hideClosureInitialization = false

[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "\t" }
